language: c
os: linux
install:
  - |-
    ( cd
        git clone -b v0.5.1 --depth=1 https://github.com/gbdev/rgbds
        sudo make -C rgbds install
        rm -rf rgbds
        sudo apt-get install wget p7zip-full
    )
before_script:
  - |-
    function check_status() {
      if ! git diff-index --quiet --ignore-submodules=all HEAD --; then
        echo 'Uncommitted changes detected:';
        git diff-index HEAD --;
        return 1;
      fi;
    }
  - wget -O roms.7z 'https://tcrf.net/images/3/33/Pok%C3%A9mon_Gold_-_Spaceworld_1997_Demo_%28Debug%29.7z'
  - 7z e roms.7z
  - mv P*\(Debug\).sgb baserom.gb
  - rm -f roms.7z P*\(Header\ Fixed\).sgb
script:
  - make -j2 compare
