name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  rgbds_version: v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout rgbds
        uses: actions/checkout@v6
        with:
          path: rgbds
          ref: ${{ env.rgbds_version }}
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison libpng-dev pkg-config
          sudo make -j$(nproc) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Cache baserom
        id: cache-baserom
        uses: actions/cache@v5
        with:
          path: baserom.gb
          key: ${{ runner.os }}-baserom

      - name: Download baserom
        if: steps.cache-baserom.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install wget p7zip-full
          wget -O roms.7z 'https://tcrf.net/images/3/33/Pok%C3%A9mon_Gold_-_Spaceworld_1997_Demo_%28Debug%29.7z'
          7z e roms.7z
          mv P*\(Debug\).sgb baserom.gb
          rm -f roms.7z P*\(Header\ Fixed\).sgb

      - name: Compare
        run: |
          make -j$(nproc) compare
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi
